version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
